name: 'cache-build-artifact'
description: >-
  Caches a tarred file or directory into a short-lived artifact for use with
  later jobs.
inputs:
  path:
    description: 'Path of file or files to archive'
    required: true
    default: './'
  archive-name:
    description: 'The name of the archive'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: 'Set archive name ðŸ“‡'
      id: 'name'
      run: |-
        if [ -n "${{ inputs.archive-name }}" ]; then
          echo "::set-output name=archive-name::'${{ inputs.archive-name }}'"
        else
          echo "::set-output name=archive-name::'build-${{ github.sha }}-${{ github.run_attempt }}'"
        fi
      shell: 'bash'
    - name: 'Tar files ðŸ¤'
      run: >-
        printf "MY CWD IS\n";
        printf "$(pwd)\n";
        printf "${{ inputs.path }}\n";
        printf "$(ls -lha)\n";
        printf tar --create
          --file "/${{ steps.name.outputs.archive-name }}.tar"
          "${{ inputs.path }}\n";
        tar --create
          --file "/${{ steps.name.outputs.archive-name }}.tar"
          "${{ inputs.path }}";
      shell: 'bash'
    - name: 'Cache build ðŸ§©'
      uses: 'actions/upload-artifact@v3'
      with:
        name: '${{ steps.name.outputs.archive-name }}'
        path: '/${{ steps.name.outputs.archive-name }}.tar'
        retention-days: 1
