name: 'retrieve-build-artifact'
description: >-
  Retrieves a tarred file or directory into a short-lived artifact for use with
  later jobs.
inputs:
  path:
    description: 'Path of file or files to archive'
    required: true
    default: './'
  archive-name:
    description: 'The name of the archive'
    required: true
    default: 'build-${{ env.GITHUB_SHA }}'
runs:
  using: 'composite'
  steps:
    - name: 'Retrieve build 🧩'
      uses: 'actions/download-artifact@v3'
      with:
        name: '${{ inputs.archive-name }}'
        path: '${{ inputs.archive-name }}'
    - name: 'Un-tar files 🤐'
      run: 'tar --extract --file "${{ inputs.archive-name }}" --directory "${{ inputs.path }}"'
      shell: 'bash'
