name: 'retrieve-build-artifact'
description: >-
  Retrieves a tarred file or directory into a short-lived artifact for use with
  later jobs.
inputs:
  path:
    description: 'Path of file or files to archive'
    required: true
    default: './'
  archive-name:
    description: 'The name of the archive'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: 'Set archive name 📇'
      id: 'name'
      run: |-
        if [ -n "${{ inputs.archive-name }}" ]; then
          echo "::set-output name=archive-name::${{ inputs.archive-name }}"
        else
          echo "::set-output name=archive-name::build-${{ github.sha }}"
        fi
      shell: 'bash'
    - name: 'Retrieve build 🧩'
      id: 'download-artifact'
      uses: 'actions/download-artifact@v3'
      with:
        name: '${{ steps.name.outputs.archive-name }}'
        path: '/tmp/${{ steps.name.outputs.archive-name }}.zip'
    - name: 'Un-ziptar files 🤐'
      run: |-
        which ls;
        ls --help;
        ls --version;
        ls -v;
        ls -lha "/tmp/";
        ls -lha "${{ steps.download-artifact.outputs.download-path }}";
        tarfile=$( \
          unzip -Z -1 \
            "${{ steps.download-artifact.outputs.download-path }}" \
            -d "/tmp/" \
        );
        tar --extract \
          --file "$tarfile" \
          --directory "${{ inputs.path }}";
      shell: 'bash'
